spring:
  application:
    name: iFile-Server
server:
  port: 7001
eureka:
  client:
    register-with-eureka: false # 是否将自己注册到Eureka Server
    fetch-registry: false # 是否从Eureka Server获取注册信息
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/