spring:
  application:
    name: Service File
  data:
    cassandra:
      cluster-name: Test Cluster
      keyspace-name: ifile
      contact-points: 106.12.130.1
      port: 9042
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

